# Generated by Django 5.2.6 on 2025-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProducts', '0003_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-create_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть товар из магазина', verbose_name='Активен'),
        ),
    ]
