# Generated by Django 5.2.6 on 2025-09-25 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProducts', '0005_remove_product_category_category_create_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-create_at'], 'verbose_name': 'Товар для продажи', 'verbose_name_plural': 'товары для продажи'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'изображения продуктов'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category', 'title'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'подкатегории'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appProducts.product', verbose_name='Товар'),
        ),
    ]
