# Generated by Django 5.2.1 on 2025-09-27 14:00

import appProducts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProducts', '0009_contactmessage_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/', validators=[appProducts.validators.validate_image_size, appProducts.validators.validate_image_extension], verbose_name='Изображение подкатегории'),
        ),
    ]
